inherit_gem:
  rubocop-rootstrap:
    - config/rails_edge.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn

Lint/UnusedMethodArgument:
  Exclude:
    - spec/support/devise_token_auth_overrides.rb

Layout/LineLength:
  Exclude:
    - db/migrate/20161011184702_devise_create_admin_users.rb
    - db/migrate/20161011151353_devise_create_users.rb
    - db/migrate/20161027190856_create_delayed_jobs.rb
    - db/migrate/20181102142200_create_active_storage_tables.active_storage.rb

Rails/Delegate:
  Exclude:
    - app/controllers/api/concerns/act_as_api_request.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/api/v1/api_controller.rb
